export const destinations = [
  {
    id: 'tokyo-japan',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    category: 'Neon Cyberpunk Cities',
    tagline: 'Where ancient shrines meet neon-drenched sky-scrapers',
    description:
      'An electric metropolis where centuries-old traditions fuse seamlessly with futuristic technology, Michelin-starred culinary artistry, and vibrant subcultures.',
    heroImage: '/images/tokyo.jpg',
    galleryImages: [
      'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?auto=format&fit=crop&w=800&q=80',
    ],
    lat: 35.6762,
    lng: 139.6503,
    rating: 4.95,
    reviewsCount: 1420,
    matchScore: 98,
    estimatedBudgetPerDay: 180,
    currency: 'JPY',
    bestSeason: 'March – May & Sept – Nov',
    visaRequirement: 'Visa-free for 90 days (68+ countries)',
    tags: ['Cyberpunk', 'Culinary', 'Culture', 'High-Speed Rail'],
    highlights: [
      'Shibuya Crossing & Sky Observatory',
      'TeamLab Planets Immersive Art',
      'Tsukiji Outer Market Tasting Tour',
    ],
    weather: { temp: 18, condition: 'Clear', icon: 'Sun', humidity: 52 },
  },
  {
    id: 'reykjavik-iceland',
    name: 'Reykjavík & The Highlands',
    country: 'Iceland',
    region: 'Europe',
    category: 'Nordic Wilderness',
    tagline: 'Land of fire, emerald aurora glaciers, and geothermal springs',
    description:
      'Venture into primeval volcanic landscapes, cascading basalt waterfalls, crystalline ice caves, and unwind in world-renowned thermal lagoons under the Northern Lights.',
    heroImage: '/images/iceland.jpg',
    galleryImages: [
      'https://images.unsplash.com/photo-1529963183134-61a90db47eaf?auto=format&fit=crop&w=800&q=80',
    ],
    lat: 64.1466,
    lng: -21.9426,
    rating: 4.92,
    reviewsCount: 980,
    matchScore: 96,
    estimatedBudgetPerDay: 260,
    currency: 'ISK',
    bestSeason: 'Sept – March (Aurora) or June – Aug (Midnight Sun)',
    visaRequirement: 'Schengen Visa regulations apply',
    tags: ['Aurora', 'Hot Springs', 'Glaciers', 'Adventure'],
    highlights: [
      'Blue Lagoon & Sky Lagoon Geothermal Spa',
      'Golden Circle Geysir & Gullfoss',
      'Katla Glacier Ice Cave Expedition',
    ],
    weather: {
      temp: 4,
      condition: 'Chilly & Clear',
      icon: 'CloudSnow',
      humidity: 78,
    },
  },
  {
    id: 'bali-indonesia',
    name: 'Bali & Nusa Penida',
    country: 'Indonesia',
    region: 'Southeast Asia',
    category: 'Tropical Sanctuaries',
    tagline: 'Emerald rice terraces, spiritual water temples & oceanic cliffs',
    description:
      'An island paradise teeming with spiritual serenity in Ubud, dramatic coastal surf breaks in Uluwatu, and secluded turquoise coves in Nusa Penida.',
    heroImage: '/images/bali.jpg',
    galleryImages: [
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=800&q=80',
    ],
    lat: -8.4095,
    lng: 115.1889,
    rating: 4.88,
    reviewsCount: 2310,
    matchScore: 95,
    estimatedBudgetPerDay: 75,
    currency: 'IDR',
    bestSeason: 'April – October (Dry Season)',
    visaRequirement: 'Visa on Arrival (VoA) 30 days',
    tags: ['Tropical', 'Wellness', 'Surfing', 'Temples'],
    highlights: [
      'Tegallalang Sacred Rice Terraces',
      'Uluwatu Sunset Fire Dance',
      'Kelingking T-Rex Beach Viewpoint',
    ],
    weather: {
      temp: 29,
      condition: 'Tropical Warmth',
      icon: 'Sun',
      humidity: 75,
    },
  },
  {
    id: 'zermatt-switzerland',
    name: 'Zermatt & The Matterhorn',
    country: 'Switzerland',
    region: 'Europe',
    category: 'Alpine Escapes',
    tagline: 'Iconic pyramidal alpine peaks, pristine powder & luxury chalets',
    description:
      'A car-free alpine wonderland at the foot of the legendary Matterhorn peak, featuring the highest cable car in Europe and pristine glacier ski routes.',
    heroImage: '/images/zermatt.jpg',
    galleryImages: [
      'https://images.unsplash.com/photo-1491557345352-5929e343eb89?auto=format&fit=crop&w=800&q=80',
    ],
    lat: 45.9765,
    lng: 7.7491,
    rating: 4.96,
    reviewsCount: 840,
    matchScore: 94,
    estimatedBudgetPerDay: 320,
    currency: 'CHF',
    bestSeason: 'Dec – April (Skiing) or July – Sept (Hiking)',
    visaRequirement: 'Schengen Visa regulations apply',
    tags: ['Alpine', 'Skiing', 'Luxury', 'Scenic Trains'],
    highlights: [
      'Gornergrat Cogwheel Railway',
      'Matterhorn Glacier Paradise 3,883m',
      'Five Lakes Alpine Hike (5-Seenweg)',
    ],
    weather: {
      temp: 2,
      condition: 'Snowy Peak',
      icon: 'CloudSnow',
      humidity: 65,
    },
  },
  {
    id: 'cairo-egypt',
    name: 'Cairo & Giza',
    country: 'Egypt',
    region: 'Middle East & Africa',
    category: 'Cultural Heritage',
    tagline: 'Colossal ancient wonders, Nile feluccas & bustling bazaars',
    description:
      'Immerse in the timeless cradle of civilization with the Great Pyramids of Giza, the newly opened Grand Egyptian Museum, and twilight cruises on the Nile.',
    heroImage: '/images/cairo.jpg',
    galleryImages: [
      'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=800&q=80',
    ],
    lat: 30.0444,
    lng: 31.2357,
    rating: 4.79,
    reviewsCount: 1650,
    matchScore: 91,
    estimatedBudgetPerDay: 85,
    currency: 'EGP',
    bestSeason: 'October – April (Mild weather)',
    visaRequirement: 'e-Visa available online (30 days)',
    tags: ['History', 'Pyramids', 'Nile Cruise', 'Archaeology'],
    highlights: [
      'Great Pyramid of Khufu & Sphinx',
      'Grand Egyptian Museum (GEM)',
      'Khan el-Khalili 14th-century Bazaar',
    ],
    weather: { temp: 26, condition: 'Sunny & Warm', icon: 'Sun', humidity: 38 },
  },
  {
    id: 'banff-canada',
    name: 'Banff & Lake Louise',
    country: 'Canada',
    region: 'North America',
    category: 'Alpine Escapes',
    tagline: 'Electric turquoise glacial lakes framed by the Canadian Rockies',
    description:
      'Surreal glacier-fed turquoise waters, towering pine forests, thermal springs, and scenic wildlife sightings along the world-famous Icefields Parkway.',
    heroImage: '/images/banff.jpg',
    galleryImages: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    ],
    lat: 51.1784,
    lng: -115.5708,
    rating: 4.93,
    reviewsCount: 1120,
    matchScore: 97,
    estimatedBudgetPerDay: 210,
    currency: 'CAD',
    bestSeason: 'June – Sept (Lakes) or Dec – March (Skiing)',
    visaRequirement: 'eTA required for visa-exempt foreign nationals',
    tags: ['Glacial Lakes', 'Hiking', 'Canoeing', 'Wildlife'],
    highlights: [
      'Moraine Lake & Lake Louise Canoeing',
      'Peyto Lake Wolf-Shaped Panorama',
      'Banff Upper Hot Springs Soak',
    ],
    weather: {
      temp: 12,
      condition: 'Crisp & Sunny',
      icon: 'Sun',
      humidity: 45,
    },
  },
  {
    id: 'amalfi-italy',
    name: 'Amalfi Coast & Positano',
    country: 'Italy',
    region: 'Europe',
    category: 'Trending',
    tagline: 'Pastel cliffside villas cascading into the azure Tyrrhenian Sea',
    description:
      'Dramatic vertical cliffs dressed in pastel villas, fragrant lemon groves, cliffside trattorias, and yacht cruises navigating the crystalline waters of Capri.',
    heroImage: '/images/amalfi.jpg',
    galleryImages: [
      'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80',
    ],
    lat: 40.634,
    lng: 14.6027,
    rating: 4.91,
    reviewsCount: 1890,
    matchScore: 99,
    estimatedBudgetPerDay: 290,
    currency: 'EUR',
    bestSeason: 'May – June & September (Avoid peak August)',
    visaRequirement: 'Schengen Visa regulations apply',
    tags: ['Coastal', 'Romance', 'Fine Dining', 'Scenic Drive'],
    highlights: [
      'Path of the Gods (Sentiero degli Dei)',
      'Private Speedboat to Capri Blue Grotto',
      'Sunset Limoncello in Positano',
    ],
    weather: {
      temp: 24,
      condition: 'Mediterranean Breeze',
      icon: 'Sun',
      humidity: 60,
    },
  },

];
